logger:
  mode: "debug"
  level: "warn"

server:
  http: 
    host: '0.0.0.0'
    port: '8080'

database:
  mysql:
    driver: mysql
    dsn: "wzs:test@tcp(localhost:3306)/xgxw?timeout=3s&charset=utf8&parseTime=True&loc=Local"
    keep_alive: 300
    max_opens: 20
    max_idles: 3

auth:
  key: "brysjhhrsl"
